[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clamm = "7PQg31yGoMQXDwkSC6FJYy23YaWX69LkSbPpLBNEfS34"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rowla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
